# Generated by Django 5.0.11 on 2025-02-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('temp_c', models.JSONField()),
                ('wind_kph', models.JSONField()),
                ('cloud', models.JSONField()),
            ],
        ),
    ]
